export const DEMOS = [
  // ─── RETAIL ──────────────────────────────────────────────────────────────────
  {
    code: '01',
    sector: 'Retail',
    channel: 'Chat',
    title: 'Recomendador de producto',
    tagline: 'Entiende una necesidad y recomienda producto en stock sin inventar precio ni disponibilidad.',
    url: 'runnersandco.com',
    agentName: 'Asistente de tienda',
    avatar: '🛍️',
    kpis: ['CTR', 'Add-to-cart', 'Conversión', 'Ticket medio', 'Devoluciones'],
    fakePage: {
      type: 'shop',
      logo: 'Runners&Co',
      links: ['Hombre', 'Mujer', 'Ofertas', 'Guía de tallas'],
      activeLink: -1,
      eyebrow: 'Nueva colección SS26',
      heading: 'Corre con la pisada a tu favor',
      sub: 'Envío gratis a partir de 60 € · Devoluciones en 30 días.',
      cta: 'Ver colección',
      sectionTitle: 'Más vendidos en running',
      products: [
        { emoji: '👟', name: 'Asics Gel-Kayano 30', price: '94,90 €' },
        { emoji: '👟', name: 'Brooks Adrenaline GTS 23', price: '99,00 €' },
        { emoji: '👟', name: 'New Balance 860v13', price: '89,00 €' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Hola, busco zapatillas para correr. Tengo pisada pronadora y presupuesto de unos 100 €.' },
      { kind: 'sys', text: 'Consultando catálogo, stock y precio en tiempo real…' },
      { kind: 'agent', text: 'Estas tres opciones encajan con tu pisada y presupuesto, todas en stock:' },
      {
        kind: 'cards',
        cards: [
          { name: 'Asics Gel-Kayano 30', price: '94,90 €', stock: 'En stock · 3 tallas', why: 'Estabilidad para pisada pronadora, soporte medial en entresuela.' },
          { name: 'Brooks Adrenaline GTS 23', price: '99,00 €', stock: 'En stock', why: 'Amortiguación guiada, la más elegida por perfiles similares.' },
          { name: 'New Balance 860v13', price: '89,00 €', stock: 'Últimas unidades', why: 'Buena relación estabilidad/precio, dentro de tu presupuesto.' },
        ],
      },
      { kind: 'user', text: 'Me quedo con las Brooks, talla 42.' },
      { kind: 'agent', text: 'Añadidas al carrito: Brooks Adrenaline GTS 23, talla 42. ¿Quieres que te avise si bajan de precio?' },
    ],
  },
  {
    code: '03',
    sector: 'Retail',
    channel: 'Voz',
    title: 'Recuperación de carritos',
    tagline: 'Llama al cliente que abandonó el carrito, resuelve la duda y cierra el pedido en la misma llamada.',
    url: 'runnersandco.com/tienda',
    agentName: 'Asistente Runners&Co',
    avatar: '🛒',
    kpis: ['Tasa de recuperación', 'Ingresos recuperados', 'Duración media', 'Pedidos generados', 'CSAT de voz'],
    fakePage: {
      type: 'shop',
      logo: 'Runners&Co',
      links: ['Hombre', 'Mujer', 'Ofertas', 'Guía de tallas'],
      activeLink: -1,
      eyebrow: 'Nueva colección SS26',
      heading: 'Corre con la pisada a tu favor',
      sub: 'Envío gratis a partir de 60 € · Devoluciones en 30 días.',
      cta: 'Ver colección',
      sectionTitle: 'Más vendidos en running',
      products: [
        { emoji: '👟', name: 'New Balance 860v13', price: '89,00 €' },
        { emoji: '👟', name: 'Hoka Clifton 9', price: '139,00 €' },
        { emoji: '👟', name: 'On Cloudmonster', price: '159,00 €' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada saliente · cliente Laura M. · carrito abandonado hace 18 h' },
      { kind: 'agent', text: 'Hola Laura, soy el asistente de Runners&Co. Ayer viste unas zapatillas y las dejaste en el carrito. ¿Te ayudo a completar el pedido?' },
      { kind: 'user', text: 'Sí, pero no sé si me van a quedar bien con mi pisada supinadora.' },
      { kind: 'agent', text: 'Las New Balance 860v13 que tienes guardadas son ideales para pisada supinadora: cushioning amplio y amortiguación neutra. ¿Te las envío en talla 39?' },
      { kind: 'user', text: 'Sí, y ¿cuándo llegan?' },
      { kind: 'sys', text: 'Verificando stock talla 39 · Calculando plazo de envío exprés…' },
      { kind: 'agent', text: 'En stock. Con envío exprés gratuito llegan mañana antes de las 14:00 h. ¿Proceso el pedido?' },
      { kind: 'user', text: 'Sí, adelante.' },
      { kind: 'sys', text: 'Generando pedido · Cargando método de pago habitual…' },
      { kind: 'agent', text: 'Pedido #9234 confirmado. Recibirás el email de confirmación en un momento. ¡Buena carrera, Laura!' },
      { kind: 'call_end', text: '✓ Llamada completada · Pedido #9234 generado · 89,00 €' },
    ],
  },
  {
    code: '06',
    sector: 'Retail',
    channel: 'Automatizacion',
    title: 'Automatización de devoluciones',
    tagline: 'Sin intervención humana: solicitud, verificación, aprobación y reembolso en un único flujo.',
    url: 'devoluciones.runnersandco.com',
    agentName: 'Devoluciones automáticas',
    avatar: '📦',
    kpis: ['Tiempo de ciclo', 'Straight-through processing', 'Fraude detectado', 'Coste por devolución', 'Reembolsos fallidos'],
    fakePage: {
      type: 'returns',
      logo: 'Runners&Co',
      links: ['Pedidos', 'Devoluciones', 'Contacto'],
      activeLink: 1,
      heading: 'Devuelve tu pedido en 3 pasos',
      sub: 'Sin colas de atención: la mayoría de devoluciones se resuelven al momento.',
      steps: [
        { label: 'Solicita la devolución', desc: 'Indica el pedido y el motivo' },
        { label: 'Envía el paquete', desc: 'Con la etiqueta que te enviamos' },
        { label: 'Recibe tu reembolso', desc: 'En 2-3 días tras la recepción' },
      ],
      formFields: ['Número de pedido', 'Email de la compra'],
      formButton: 'Buscar pedido',
    },
    steps: [
      { kind: 'user', text: 'Quiero devolver un artículo del pedido #7734, no me convence.' },
      { kind: 'sys', text: 'Recuperando pedido · verificando plazo y estado…' },
      { kind: 'sys', text: 'Analizando evidencia del artículo · comprobando antifraude…' },
      { kind: 'agent', text: 'Devolución aprobada automáticamente. Aquí tienes tu etiqueta RMA — lleva el paquete a tu punto de envío.' },
      { kind: 'sys', text: 'Artículo recibido en almacén · reembolso de 42,90 € iniciado' },
      { kind: 'agent', text: 'Reembolso confirmado. El importe llegará a tu método de pago en 2-3 días laborables.' },
      { kind: 'banner', text: '✓ Completado sin intervención humana' },
    ],
  },

  // ─── ACTIVIDADES DEPORTIVAS ───────────────────────────────────────────────────
  {
    code: '09',
    sector: 'Actividades Deportivas',
    channel: 'Chat',
    title: 'Reservas de pistas',
    tagline: 'Consulta disponibilidad, confirma la reserva y procesa el pago en una sola conversación.',
    url: 'padelclubmadrid.com',
    agentName: 'Asistente PadelClub',
    avatar: '🎾',
    kpis: ['Reservas completadas', 'Tiempo medio de reserva', 'Tasa de no-show', 'Ocupación de pistas', 'CSAT'],
    fakePage: {
      type: 'contact',
      logo: 'PadelClub Madrid',
      links: ['Pistas', 'Socios', 'Torneos', 'Contacto'],
      activeLink: 3,
      heading: '¿En qué podemos ayudarte?',
      phone: '91 555 22 33',
      departments: [
        { icon: '🎾', label: 'Reservas de pistas', desc: 'Disponibilidad y confirmación online' },
        { icon: '👤', label: 'Gestión de socios', desc: 'Abonos, renovaciones y bonos' },
        { icon: '🏆', label: 'Torneos y eventos', desc: 'Inscripción y resultados' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Quiero reservar una pista de pádel para mañana sábado a las 10.' },
      { kind: 'sys', text: 'Consultando disponibilidad de pistas…' },
      { kind: 'agent', text: 'Para mañana a las 10:00 h tengo disponibles la Pista 2 (cubierta) y la Pista 4 (exterior). ¿Cuántos jugadores sois?' },
      { kind: 'user', text: 'Somos 4 y preferimos cubierta.' },
      { kind: 'agent', text: 'Pista 2 disponible de 10:00 a 11:30 h — 24 €. ¿La reservo a tu nombre?' },
      { kind: 'user', text: 'Sí, para Carlos Méndez.' },
      { kind: 'sys', text: 'Registrando reserva · procesando pago con tarjeta guardada…' },
      { kind: 'agent', text: 'Reserva confirmada. Recibirás el justificante en el email de tu cuenta de socio.' },
      { kind: 'banner', text: '✓ Pista 2 · Sábado 10:00–11:30 h · 24 € cobrados' },
    ],
  },
  {
    code: '11',
    sector: 'Actividades Deportivas',
    channel: 'Voz',
    title: 'Renovación de abonos',
    tagline: 'Llama al socio antes del vencimiento, ofrece la promoción de fidelidad y renueva en la misma llamada.',
    url: 'padelclubmadrid.com/socios',
    agentName: 'Asistente PadelClub',
    avatar: '🏅',
    kpis: ['Tasa de renovación', 'Churn evitado', 'Ingresos recurrentes', 'Duración media de llamada', 'CSAT'],
    fakePage: {
      type: 'contact',
      logo: 'PadelClub Madrid',
      links: ['Pistas', 'Socios', 'Torneos', 'Contacto'],
      activeLink: 1,
      heading: '¿En qué podemos ayudarte?',
      phone: '91 555 22 33',
      departments: [
        { icon: '🎾', label: 'Reservas de pistas', desc: 'Disponibilidad y confirmación online' },
        { icon: '👤', label: 'Gestión de socios', desc: 'Abonos, renovaciones y bonos' },
        { icon: '🏆', label: 'Torneos y eventos', desc: 'Inscripción y resultados' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada saliente · socio Carlos M. · abono vence en 5 días' },
      { kind: 'agent', text: 'Hola Carlos, soy el asistente del PadelClub Madrid. Tu abono anual vence el próximo viernes. ¿Quieres renovarlo ahora?' },
      { kind: 'user', text: 'Sí, pero ¿hay alguna promoción?' },
      { kind: 'agent', text: 'Como socio de más de 2 años tienes un 15 % de descuento: el abono anual quedaría en 340 € en lugar de 400 €.' },
      { kind: 'user', text: 'Perfecto, renuévalo.' },
      { kind: 'sys', text: 'Procesando renovación · cargando método de pago habitual…' },
      { kind: 'agent', text: 'Renovado hasta el 31 de julio de 2027. El cargo de 340 € se realizará en tu tarjeta terminada en 4821. El recibo llega ahora mismo.' },
      { kind: 'call_end', text: '✓ Abono renovado · Descuento del 15 % aplicado' },
    ],
  },
  {
    code: '17',
    sector: 'Actividades Deportivas',
    channel: 'Integracion',
    title: 'Panel de gestión del club',
    tagline: 'Consulta CRM, reservas y pagos en un único flujo para operar sobre datos reales con trazabilidad completa.',
    url: 'panel.sportclub360.es',
    agentName: 'Agente SportClub360',
    avatar: '🏟️',
    kpis: ['Operaciones completadas', 'Reservas gestionadas', 'Renovaciones activadas', 'Disponibilidad', 'Trazabilidad de acciones'],
    fakePage: {
      type: 'portal',
      logo: 'SportClub360',
      links: ['Socios', 'Reservas', 'Eventos', 'Facturación'],
      activeLink: 0,
      heading: 'Panel de gestión del club',
      sub: 'Acceso administrador · Datos en tiempo real',
      menuItems: ['Búsqueda de socio', 'Gestión de reservas', 'Eventos y torneos', 'Facturación y abonos'],
      activeMenu: 0,
      searchPlaceholder: 'Buscar socio o reserva…',
      stats: [
        { label: 'Socios activos', value: '1.247' },
        { label: 'Reservas hoy', value: '84' },
      ],
    },
    steps: [
      { kind: 'user', text: '¿Cuántos abonos activos hay este mes y cuántos vencen en los próximos 7 días?' },
      { kind: 'multi_query', queries: ['CRM socios', 'Sistema reservas', 'Facturación'] },
      {
        kind: 'data_panel',
        fields: [
          { label: 'Abonos activos', value: '1.247' },
          { label: 'Vencen en 7 días', value: '83' },
          { label: 'Sin renovar', value: '31' },
          { label: 'Ratio renovación', value: '63 %' },
        ],
      },
      { kind: 'agent', text: '1.247 socios activos. Esta semana vencen 83 abonos — 31 aún no han renovado. ¿Activo la campaña de recordatorio con descuento?' },
      { kind: 'user', text: 'Sí, actívala con un 10 % de descuento.' },
      { kind: 'sys', text: 'Preparando campaña · verificando datos de contacto…' },
      { kind: 'agent', text: 'Campaña lista para 31 socios con enlace de renovación y descuento del 10 %. ¿Confirmas el envío?' },
      { kind: 'user', text: 'Confirmar.' },
      { kind: 'sys', text: 'Enviando SMS y email · registrando promoción en sistema…' },
      { kind: 'banner', text: '✓ 31 recordatorios enviados · Descuento del 10 % aplicado' },
    ],
  },

  // ─── SALUD ────────────────────────────────────────────────────────────────────
  {
    code: '21',
    sector: 'Salud',
    channel: 'Chat',
    title: 'Triaje de síntomas',
    tagline: 'Evalúa los síntomas del paciente, aplica el protocolo de triaje y reserva cita con la urgencia adecuada.',
    url: 'clinicaplus.es',
    agentName: 'Asistente ClinicaPlus',
    avatar: '🩺',
    kpis: ['Triajes completados', 'Derivaciones urgentes correctas', 'Citas reservadas', 'Tiempo de respuesta', 'CSAT'],
    fakePage: {
      type: 'clinic',
      logo: 'ClinicaPlus',
      links: ['Inicio', 'Especialidades', 'Citas', 'Mi Historial'],
      activeLink: 2,
      heading: 'Tu salud, nuestro centro',
      searchPlaceholder: 'Buscar especialidad o médico…',
      doctors: [
        { name: 'Dr. Ruiz', specialty: 'Medicina general', available: 'Hoy' },
        { name: 'Dra. Vega', specialty: 'Dermatología', available: 'Mañana' },
        { name: 'Dr. Santos', specialty: 'Cardiología', available: 'Vie 26' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Llevo 3 días con fiebre de 38,5 y dolor de garganta fuerte.' },
      { kind: 'sys', text: 'Evaluando síntomas · aplicando protocolo de triaje…' },
      { kind: 'agent', text: 'Entendido. ¿Tienes dificultad para tragar o respirar, ganglios inflamados o manchas en la garganta?' },
      { kind: 'user', text: 'Tengo ganglios inflamados y al tragar me duele bastante.' },
      { kind: 'agent', text: 'Tus síntomas sugieren una posible faringoamigdalitis. Recomiendo visita médica en menos de 24 h. ¿Te reservo cita para esta tarde?' },
      { kind: 'user', text: 'Sí, por favor.' },
      { kind: 'sys', text: 'Verificando agenda de medicina general…' },
      { kind: 'agent', text: 'Cita reservada para hoy a las 17:30 h con el Dr. Ruiz. Recibirás confirmación en tu móvil.' },
      { kind: 'banner', text: '✓ Cita reservada · Hoy 17:30 h · Dr. Ruiz' },
    ],
  },
  {
    code: '18',
    sector: 'Salud',
    channel: 'Voz',
    title: 'Citas médicas por voz',
    tagline: 'Gestiona citas entrantes por teléfono: identifica al paciente, consulta agenda y confirma la reserva.',
    url: 'clinicaplus.es/citas',
    agentName: 'Asistente ClinicaPlus',
    avatar: '📅',
    kpis: ['Citas gestionadas', 'Tiempo medio de llamada', 'Errores de agenda', 'No-shows', 'CSAT de voz'],
    fakePage: {
      type: 'clinic',
      logo: 'ClinicaPlus',
      links: ['Inicio', 'Especialidades', 'Citas', 'Mi Historial'],
      activeLink: 2,
      heading: 'Tu salud, nuestro centro',
      searchPlaceholder: 'Buscar especialidad o médico…',
      doctors: [
        { name: 'Dr. Ruiz', specialty: 'Medicina general', available: 'Hoy' },
        { name: 'Dra. Vega', specialty: 'Dermatología', available: 'Mañana' },
        { name: 'Dr. Santos', specialty: 'Cardiología', available: 'Vie 26' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 900 123 456' },
      { kind: 'agent', text: 'Hola, soy el asistente de ClinicaPlus. ¿En qué puedo ayudarte?' },
      { kind: 'user', text: 'Quiero pedir cita con el dermatólogo.' },
      { kind: 'sys', text: 'Consultando agenda de dermatología…' },
      { kind: 'agent', text: 'Tengo disponibilidad el martes 29 a las 11:00 h o el jueves 31 a las 16:30 h. ¿Cuál prefieres?' },
      { kind: 'user', text: 'El jueves a las 16:30.' },
      { kind: 'agent', text: '¿A nombre de quién reservo la cita?' },
      { kind: 'user', text: 'Elena Torres.' },
      { kind: 'sys', text: 'Registrando cita · enviando confirmación por SMS…' },
      { kind: 'agent', text: 'Cita reservada, Elena. Jueves 31 a las 16:30 h con la Dra. Vega. Te envío los detalles por SMS.' },
      { kind: 'call_end', text: '✓ Cita confirmada · SMS enviado a Elena Torres' },
    ],
  },
  {
    code: '23',
    sector: 'Salud',
    channel: 'Automatizacion',
    title: 'Recordatorios de medicación',
    tagline: 'Envía el recordatorio en el canal preferido del paciente y registra la adherencia en la historia clínica.',
    url: 'clinicaplus.es/pacientes',
    agentName: 'Adherencia ClinicaPlus',
    avatar: '💊',
    kpis: ['Adherencia terapéutica', 'Confirmaciones recibidas', 'Avisos sin respuesta', 'Escalados a enfermería', 'Registros en HCE'],
    fakePage: {
      type: 'clinic',
      logo: 'ClinicaPlus',
      links: ['Inicio', 'Especialidades', 'Citas', 'Mi Historial'],
      activeLink: 3,
      heading: 'Tu salud, nuestro centro',
      searchPlaceholder: 'Buscar especialidad o médico…',
      doctors: [
        { name: 'Dr. Ruiz', specialty: 'Medicina general', available: 'Hoy' },
        { name: 'Dra. Vega', specialty: 'Dermatología', available: 'Mañana' },
        { name: 'Dr. Santos', specialty: 'Cardiología', available: 'Vie 26' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Paciente Ana M. · pauta de metformina · dosis de las 21:00 h sin confirmar' },
      { kind: 'sys', text: 'Activando canal de notificación preferido: SMS + app' },
      { kind: 'agent', text: 'Hola Ana, recuerda tomar tu dosis de metformina (500 mg) esta noche con la cena. Si ya la tomaste, confirma aquí.' },
      { kind: 'user', text: 'Ya la tomé hace un momento.' },
      { kind: 'sys', text: 'Registrando confirmación · actualizando adherencia en historia clínica…' },
      { kind: 'agent', text: 'Perfecto. Adherencia del mes: 96 %. Siguiente recordatorio mañana a las 09:00 h con el desayuno.' },
      { kind: 'banner', text: '✓ Dosis confirmada · Adherencia actualizada en HCE' },
    ],
  },

  // ─── TELECOM ──────────────────────────────────────────────────────────────────
  {
    code: '29',
    sector: 'Telecom',
    channel: 'Chat',
    title: 'Consulta de consumo y bonos',
    tagline: 'Informa del consumo en tiempo real y activa un bono adicional en la misma conversación.',
    url: 'movilplus.es/micuenta',
    agentName: 'Asistente MovilPlus',
    avatar: '📱',
    kpis: ['Consultas resueltas', 'Bonos activados', 'Tiempo de resolución', 'Escalados a agente', 'CSAT'],
    fakePage: {
      type: 'generic-service',
      logo: 'MovilPlus',
      links: ['Tarifas', 'Mi cuenta', 'Ayuda', 'Contacto'],
      activeLink: 1,
      tagline: 'Tu operador de confianza',
      heading: 'Todo en una sola tarifa',
      phone: '900 900 900',
      tiles: [
        { icon: '📱', label: 'Mis tarifas', desc: 'Consulta y cambia tu plan' },
        { icon: '📊', label: 'Consumo', desc: 'Datos, llamadas y SMS' },
        { icon: '🛡️', label: 'Soporte', desc: 'Averías e incidencias' },
      ],
    },
    steps: [
      { kind: 'user', text: '¿Cuántos gigas me quedan este mes?' },
      { kind: 'sys', text: 'Consultando consumo en tiempo real…' },
      { kind: 'agent', text: 'Te quedan 4,2 GB de tus 30 GB mensuales. El ciclo se renueva el día 5. A este ritmo los agotarás en 2 días.' },
      { kind: 'user', text: '¿Puedo comprar un bono adicional?' },
      { kind: 'agent', text: 'Sí. Tienes tres opciones: 5 GB por 3 €, 15 GB por 7 € o 30 GB por 12 €. ¿Cuál quieres?' },
      { kind: 'user', text: 'El de 15 GB.' },
      { kind: 'sys', text: 'Activando bono de 15 GB…' },
      { kind: 'agent', text: 'Bono activado. Ya tienes 19,2 GB disponibles. El cargo de 7 € aparecerá en tu próxima factura.' },
      { kind: 'banner', text: '✓ Bono 15 GB activado · Total disponible: 19,2 GB' },
    ],
  },
  {
    code: '26',
    sector: 'Telecom',
    channel: 'Voz',
    title: 'Anti-churn por voz',
    tagline: 'Detecta intención de baja, ofrece la contraoferta personalizada y retiene al cliente en la llamada.',
    url: 'movilplus.es/contacto',
    agentName: 'Asistente MovilPlus',
    avatar: '🔄',
    kpis: ['Bajas retenidas', 'Tasa de retención', 'Coste de retención', 'Duración de llamada', 'NPS post-llamada'],
    fakePage: {
      type: 'generic-service',
      logo: 'MovilPlus',
      links: ['Tarifas', 'Mi cuenta', 'Ayuda', 'Contacto'],
      activeLink: 3,
      tagline: 'Tu operador de confianza',
      heading: 'Todo en una sola tarifa',
      phone: '900 900 900',
      tiles: [
        { icon: '📱', label: 'Mis tarifas', desc: 'Consulta y cambia tu plan' },
        { icon: '📊', label: 'Consumo', desc: 'Datos, llamadas y SMS' },
        { icon: '🛡️', label: 'Soporte', desc: 'Averías e incidencias' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada saliente · cliente Miguel A. · solicitud de portabilidad detectada' },
      { kind: 'agent', text: 'Hola Miguel, soy el asistente de MovilPlus. Vimos que pediste información sobre portabilidad. ¿Puedo ayudarte?' },
      { kind: 'user', text: 'Llevo meses pagando 45 € y la competencia me ofrece lo mismo por 28.' },
      { kind: 'agent', text: 'Entiendo. Como cliente de 4 años puedo ofrecerte nuestro plan Fidelidad: 30 GB + llamadas ilimitadas por 27 € al mes durante 12 meses.' },
      { kind: 'user', text: 'Eso está bien. ¿Y si hay algún problema puedo cancelar?' },
      { kind: 'agent', text: 'Sin permanencia. ¿Lo activo ahora?' },
      { kind: 'user', text: 'Sí, de acuerdo.' },
      { kind: 'sys', text: 'Actualizando plan · cancelando solicitud de portabilidad…' },
      { kind: 'agent', text: 'Perfecto. Tu nuevo plan entra en vigor mañana. Recibirás el contrato por email.' },
      { kind: 'call_end', text: '✓ Baja cancelada · Plan Fidelidad activado a 27 €/mes' },
    ],
  },
  {
    code: '31',
    sector: 'Telecom',
    channel: 'Automatizacion',
    title: 'Diagnóstico automático de averías',
    tagline: 'Diagnostica la avería de forma remota, aplica el reinicio y verifica la conexión sin técnico.',
    url: 'movilplus.es/soporte',
    agentName: 'NOC Automático MovilPlus',
    avatar: '🔧',
    kpis: ['Averías resueltas sin técnico', 'Tiempo medio de resolución', 'Visitas técnicas evitadas', 'Falsos positivos', 'CSAT'],
    fakePage: {
      type: 'generic-service',
      logo: 'MovilPlus',
      links: ['Tarifas', 'Mi cuenta', 'Ayuda', 'Contacto'],
      activeLink: 2,
      tagline: 'Tu operador de confianza',
      heading: 'Todo en una sola tarifa',
      phone: '900 900 900',
      tiles: [
        { icon: '📡', label: 'Estado de red', desc: 'Cobertura y velocidad' },
        { icon: '🔧', label: 'Averías', desc: 'Diagnóstico remoto' },
        { icon: '📞', label: 'Soporte', desc: 'Habla con un agente' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Ticket #8812 · cliente sin señal de fibra · dirección: C/ Goya 22, Madrid' },
      { kind: 'sys', text: 'Lanzando diagnóstico remoto sobre router ONT-7843…' },
      { kind: 'sys', text: 'Resultado: pérdida de sincronía OLT desde las 03:14 h · reinicio remoto disponible' },
      { kind: 'agent', text: 'Avería detectada en tu router. Estoy aplicando un reinicio remoto — tardará unos 90 segundos.' },
      { kind: 'sys', text: 'Reinicio completado · verificando conectividad…' },
      { kind: 'agent', text: 'Conexión restaurada. Tu fibra está operativa al 100 %. Velocidad actual: 598 Mbps.' },
      { kind: 'banner', text: '✓ Avería resuelta sin visita técnica · Tiempo: 4 minutos' },
    ],
  },

  // ─── LOGÍSTICA ────────────────────────────────────────────────────────────────
  {
    code: '34',
    sector: 'Logística',
    channel: 'Chat',
    title: 'Reprogramación de entrega',
    tagline: 'El cliente indica que no estará en casa y el agente reprograma la entrega en tiempo real.',
    url: 'logisticx.es/seguimiento',
    agentName: 'Asistente LogisticX',
    avatar: '🚚',
    kpis: ['Entregas reprogramadas', 'Intentos de entrega fallidos', 'CSAT', 'Tiempo de resolución', 'Coste por reprogramación'],
    fakePage: {
      type: 'contact',
      logo: 'LogisticX',
      links: ['Seguimiento', 'Recogidas', 'Incidencias', 'Contacto'],
      activeLink: 0,
      heading: '¿Cómo podemos ayudarte?',
      phone: '91 234 56 78',
      departments: [
        { icon: '📦', label: 'Seguimiento de envíos', desc: 'Localiza tu paquete en tiempo real' },
        { icon: '📅', label: 'Gestión de entregas', desc: 'Reprogramar y redirigir' },
        { icon: '⚠️', label: 'Incidencias', desc: 'Pérdidas, daños y retrasos' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Mi pedido ES987654321 llega hoy pero no voy a estar en casa.' },
      { kind: 'sys', text: 'Consultando estado del envío…' },
      { kind: 'agent', text: 'Tu pedido está en reparto, programado para hoy entre 12:00 y 14:00 h. ¿Reprogramo para mañana o lo redirijo a un punto de recogida?' },
      { kind: 'user', text: 'Prefiero que lo dejen mañana por la tarde.' },
      { kind: 'agent', text: 'Tengo disponibles de 16:00 a 20:00 h. ¿Cuándo es mejor para ti?' },
      { kind: 'user', text: 'Entre 18:00 y 20:00.' },
      { kind: 'sys', text: 'Reprogramando entrega · notificando al repartidor…' },
      { kind: 'agent', text: 'Entrega reprogramada para mañana de 18:00 a 20:00 h. Te avisaré 30 minutos antes.' },
      { kind: 'banner', text: '✓ Entrega reprogramada · Mañana 18:00–20:00 h' },
    ],
  },
  {
    code: '33',
    sector: 'Logística',
    channel: 'Voz',
    title: 'Tracking de envío por voz',
    tagline: 'Identifica el paquete, informa del estado en tiempo real y gestiona la incidencia sin intervención humana.',
    url: 'logisticx.es/contacto',
    agentName: 'Asistente LogisticX',
    avatar: '📦',
    kpis: ['Resolución en llamada', 'Duración media', 'Reentradas en 24 h', 'Redireccionamientos gestionados', 'CSAT de voz'],
    fakePage: {
      type: 'contact',
      logo: 'LogisticX',
      links: ['Seguimiento', 'Recogidas', 'Incidencias', 'Contacto'],
      activeLink: 3,
      heading: '¿Cómo podemos ayudarte?',
      phone: '91 234 56 78',
      departments: [
        { icon: '📦', label: 'Seguimiento de envíos', desc: 'Localiza tu paquete en tiempo real' },
        { icon: '⚠️', label: 'Incidencias y reclamaciones', desc: 'Pérdidas, daños y retrasos' },
        { icon: '🚚', label: 'Recogidas a domicilio', desc: 'Programa una recogida sin coste' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 91 234 56 78' },
      { kind: 'agent', text: 'Hola, soy el asistente de LogisticX. ¿Cómo puedo ayudarte?' },
      { kind: 'user', text: 'Quiero saber dónde está mi paquete. El número de seguimiento es ES987654321.' },
      { kind: 'sys', text: 'Consultando TMS · localizando paquete ES987654321…' },
      { kind: 'agent', text: 'Tu paquete salió del centro de Madrid a las 7:14 h y está en reparto. Llegará hoy antes de las 14:00 h.' },
      { kind: 'user', text: '¿Y si no estoy en casa?' },
      { kind: 'agent', text: 'Puedo programar una segunda entrega para mañana o redirigirlo a un punto de recogida. ¿Cuál prefieres?' },
      { kind: 'user', text: 'El punto de recogida, por favor.' },
      { kind: 'sys', text: 'Localizando puntos cercanos · reservando plaza…' },
      { kind: 'agent', text: 'Listo. Tu paquete irá al punto UPS en Calle Mayor 15, disponible mañana desde las 9:00 h. Te envío el código de recogida por SMS.' },
      { kind: 'call_end', text: '✓ Llamada completada · SMS de confirmación enviado' },
    ],
  },
  {
    code: '35',
    sector: 'Logística',
    channel: 'Automatizacion',
    title: 'Optimización de rutas',
    tagline: 'Asigna automáticamente 187 entregas en 12 vehículos y recalcula cuando aparece una restricción de tráfico.',
    url: 'ops.logisticx.es/rutas',
    agentName: 'Route Optimizer LogisticX',
    avatar: '🗺️',
    kpis: ['Km ahorrados', 'Entregas en ventana', 'Rutas generadas', 'Tiempo de planificación', 'Coste por entrega'],
    fakePage: {
      type: 'contact',
      logo: 'LogisticX',
      links: ['Operaciones', 'Rutas', 'Vehículos', 'Informes'],
      activeLink: 1,
      heading: 'Centro de operaciones',
      phone: '91 234 56 79',
      departments: [
        { icon: '🗺️', label: 'Planificación de rutas', desc: 'Asignación automática optimizada' },
        { icon: '🚛', label: 'Gestión de flota', desc: 'Vehículos y conductores' },
        { icon: '📊', label: 'Informes', desc: 'KPIs de operación' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Bandeja de mañana: 187 entregas · zona Madrid Sur · 12 vehículos disponibles' },
      { kind: 'sys', text: 'Analizando tráfico, capacidades y ventanas horarias comprometidas…' },
      { kind: 'sys', text: 'Optimizando rutas con modelo VRP…' },
      { kind: 'agent', text: 'Rutas optimizadas: 12 rutas de 14–18 paradas. Ahorro estimado: −23 % en km, −1,8 h de operación.' },
      { kind: 'sys', text: 'Restricción detectada: C/ Serrano cortada por obras 08:00–14:00 h' },
      { kind: 'sys', text: 'Recalculando rutas afectadas (vehículos 4 y 7)…' },
      { kind: 'agent', text: 'Rutas 4 y 7 actualizadas. Todas las entregas dentro de ventanas comprometidas. Itinerarios enviados a dispositivos de conductores.' },
      { kind: 'banner', text: '✓ 187 entregas asignadas · −23 % km · Itinerarios notificados' },
    ],
  },

  // ─── VIAJES ───────────────────────────────────────────────────────────────────
  {
    code: '43',
    sector: 'Viajes',
    channel: 'Chat',
    title: 'Conserjería digital 24/7',
    tagline: 'Responde consultas del huésped, gestiona servicios del hotel y registra reservas sin intervención humana.',
    url: 'hotelpalaciomadrid.com',
    agentName: 'Conserje virtual',
    avatar: '🏨',
    kpis: ['Solicitudes resueltas', 'Upselling generado', 'Tiempo de respuesta', 'Reservas de servicio', 'CSAT'],
    fakePage: {
      type: 'hotel',
      logo: 'Hotel Palacio Real',
      links: ['Inicio', 'Habitaciones', 'Spa', 'Restaurante', 'Contacto'],
      activeLink: 0,
      heroEmoji: '🏛️',
      heading: 'Una experiencia única en Madrid',
      sub: 'El hotel más emblemático del centro histórico de Madrid.',
      rooms: [
        { emoji: '🛏️', name: 'Habitación Estándar', price: '120 €/noche' },
        { emoji: '🌿', name: 'Deluxe con jardín', price: '195 €/noche' },
        { emoji: '👑', name: 'Suite Junior', price: '285 €/noche' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Hola, estoy en la habitación 412. ¿A qué hora abre el spa mañana?' },
      { kind: 'sys', text: 'Consultando servicios del hotel…' },
      { kind: 'agent', text: 'El spa abre mañana a las 09:00 h. Incluye piscina, sauna y sala de relajación. ¿Quieres reservar un tratamiento?' },
      { kind: 'user', text: 'Sí, un masaje de 60 minutos para las 10:30.' },
      { kind: 'sys', text: 'Verificando disponibilidad en spa…' },
      { kind: 'agent', text: 'Disponible mañana a las 10:30 h. Masaje relajante de 60 minutos: 85 €. ¿Lo cargo a tu habitación?' },
      { kind: 'user', text: 'Sí, perfecto.' },
      { kind: 'sys', text: 'Registrando reserva en PMS…' },
      { kind: 'agent', text: 'Reserva confirmada. El masaje se cargará al checkout. Lucía te espera en recepción del spa.' },
      { kind: 'banner', text: '✓ Spa 10:30 h reservado · Cargo pendiente al checkout' },
    ],
  },
  {
    code: '40',
    sector: 'Viajes',
    channel: 'Voz',
    title: 'Reservas de hotel por voz',
    tagline: 'Recibe llamadas de reserva, verifica disponibilidad y confirma con todos los extras en la misma llamada.',
    url: 'hotelpalaciomadrid.com/reservas',
    agentName: 'Recepción Hotel Palacio',
    avatar: '🛎️',
    kpis: ['Reservas completadas', 'Ingresos por llamada', 'Extras añadidos', 'Duración media', 'CSAT de voz'],
    fakePage: {
      type: 'hotel',
      logo: 'Hotel Palacio Real',
      links: ['Inicio', 'Habitaciones', 'Spa', 'Restaurante', 'Contacto'],
      activeLink: 4,
      heroEmoji: '🏛️',
      heading: 'Una experiencia única en Madrid',
      sub: 'El hotel más emblemático del centro histórico de Madrid.',
      rooms: [
        { emoji: '🛏️', name: 'Habitación Estándar', price: '120 €/noche' },
        { emoji: '🌿', name: 'Deluxe con jardín', price: '195 €/noche' },
        { emoji: '👑', name: 'Suite Junior', price: '285 €/noche' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 91 800 00 00' },
      { kind: 'agent', text: 'Hotel Palacio Real, buenas noches. ¿En qué puedo ayudarle?' },
      { kind: 'user', text: 'Quiero reservar una habitación doble para el puente del 1 de mayo, del 30 de abril al 2 de mayo.' },
      { kind: 'sys', text: 'Verificando disponibilidad 30 abr–2 may (2 noches)…' },
      { kind: 'agent', text: 'Disponemos de una Deluxe con vistas al jardín a 195 €/noche. ¿Incluye desayuno?' },
      { kind: 'user', text: 'Sí, con desayuno. ¿Y tienen parking?' },
      { kind: 'agent', text: 'Desayuno buffet: +22 €/noche. Parking cubierto: 18 €/noche. Total 2 noches: 470 €. ¿Procedo con la reserva?' },
      { kind: 'user', text: 'Sí, a nombre de Sofía Ramos.' },
      { kind: 'sys', text: 'Registrando reserva en PMS · procesando garantía de tarjeta…' },
      { kind: 'agent', text: 'Reserva confirmada, Sofía. Recibirá el email con el localizador en unos instantes.' },
      { kind: 'call_end', text: '✓ Reserva #H-4421 confirmada · 2 noches · 470 €' },
    ],
  },
  {
    code: '44',
    sector: 'Viajes',
    channel: 'Automatizacion',
    title: 'Gestión de overbooking',
    tagline: 'Detecta el overbooking, selecciona los perfiles a reubicar, coordina el hotel alternativo y notifica a los afectados.',
    url: 'ops.hotelpalaciomadrid.com',
    agentName: 'Revenue Management IA',
    avatar: '🔁',
    kpis: ['Overbookings resueltos', 'Clientes reubicados', 'Cancelaciones evitadas', 'Coste de reubicación', 'NPS post-incidente'],
    fakePage: {
      type: 'hotel',
      logo: 'Hotel Palacio Real',
      links: ['Operaciones', 'Reservas', 'Revenue', 'Informes'],
      activeLink: 1,
      heroEmoji: '⚙️',
      heading: 'Panel de revenue management',
      sub: 'Gestión de capacidad y overbooking en tiempo real.',
      rooms: [
        { emoji: '✅', name: 'Habitaciones disponibles', price: '0' },
        { emoji: '🔴', name: 'Overbooking activo', price: '3 reservas' },
        { emoji: '🏨', name: 'Hotel alternativo', price: 'Hotel Hermano · 400 m' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Alerta: overbooking detectado · noche del 30 abr · 3 reservas sin habitación' },
      { kind: 'sys', text: 'Analizando perfiles: valor de cliente, canal de reserva, hora de llegada estimada…' },
      { kind: 'agent', text: 'Propuesta: reubicar a los 3 clientes en Hotel Hermano (misma categoría, 400 m). Precio equivalente + upgrade de habitación incluido.' },
      { kind: 'sys', text: 'Notificando a clientes afectados por email y SMS…' },
      { kind: 'agent', text: 'Cliente 1 (Lorenzo G.) acepta. Clientes 2 y 3 sin respuesta — programando llamada automática en 30 min.' },
      { kind: 'sys', text: 'Reservas en Hotel Hermano confirmadas · transporte cortesía coordinado' },
      { kind: 'banner', text: '✓ Overbooking resuelto · 3 reubicaciones · 0 cancelaciones' },
    ],
  },

  // ─── SEGUROS ──────────────────────────────────────────────────────────────────
  {
    code: '47',
    sector: 'Seguros',
    channel: 'Chat',
    title: 'Cotización de pólizas',
    tagline: 'Recoge el perfil de riesgo, calcula la prima al momento y genera una propuesta lista para contratar.',
    url: 'segurfacil.es',
    agentName: 'Asistente SegurFácil',
    avatar: '🛡️',
    kpis: ['Cotizaciones generadas', 'Conversión a contrato', 'Tiempo de cotización', 'Prima media', 'CSAT'],
    fakePage: {
      type: 'generic-service',
      logo: 'SegurFácil',
      links: ['Productos', 'Cotizar', 'Siniestros', 'Contacto'],
      activeLink: 1,
      tagline: 'Seguros para personas reales',
      heading: 'Protege lo que más te importa',
      phone: '900 900 100',
      tiles: [
        { icon: '🏠', label: 'Hogar', desc: 'Continente, contenido y responsabilidad civil' },
        { icon: '🚗', label: 'Auto', desc: 'Terceros, lunas y todo riesgo' },
        { icon: '❤️', label: 'Vida y salud', desc: 'Coberturas personales' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Quiero contratar un seguro de hogar para un piso de 90 m² en Madrid.' },
      { kind: 'sys', text: 'Cargando perfil de riesgo y catálogo de productos…' },
      { kind: 'agent', text: 'Para calcular la prima necesito saber: ¿es piso propio o de alquiler, y tienes alarma instalada?' },
      { kind: 'user', text: 'Piso propio, sin alarma.' },
      { kind: 'agent', text: 'Con ese perfil te ofrezco tres opciones: Básico 8 €/mes, Estándar 14 €/mes (robo+RC), Premium 22 €/mes (electrodomésticos+asistencia 24h). ¿Cuál prefieres?' },
      { kind: 'user', text: 'El Estándar.' },
      { kind: 'sys', text: 'Generando propuesta personalizada…' },
      { kind: 'agent', text: 'Propuesta lista: cobertura desde mañana, 14 €/mes, primer mes gratis. ¿Te envío el contrato por email para firmarlo digitalmente?' },
      { kind: 'banner', text: '✓ Cotización Estándar generada · 14 €/mes · Primer mes gratis' },
    ],
  },
  {
    code: '46',
    sector: 'Seguros',
    channel: 'Voz',
    title: 'FNOL — Primer aviso de siniestro',
    tagline: 'Recibe el primer aviso de siniestro por teléfono, abre el expediente y activa el protocolo de atención.',
    url: 'segurfacil.es/siniestros',
    agentName: 'Asistente Siniestros',
    avatar: '🚨',
    kpis: ['Expedientes abiertos', 'Tiempo de apertura', 'Datos recogidos correctamente', 'Escalados a perito', 'CSAT de urgencias'],
    fakePage: {
      type: 'generic-service',
      logo: 'SegurFácil',
      links: ['Productos', 'Cotizar', 'Siniestros', 'Contacto'],
      activeLink: 2,
      tagline: 'Seguros para personas reales',
      heading: 'Protege lo que más te importa',
      phone: '900 900 100',
      tiles: [
        { icon: '🚨', label: 'Siniestros', desc: 'Apertura y seguimiento 24h' },
        { icon: '🔧', label: 'Asistencia', desc: 'Envío de ayuda inmediata' },
        { icon: '📋', label: 'Documentación', desc: 'Partes y peritajes' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 900 900 100 · línea de siniestros' },
      { kind: 'agent', text: 'SegurFácil, servicio de siniestros. ¿Cómo puedo ayudarle?' },
      { kind: 'user', text: 'He tenido un accidente de tráfico, acabo de chocar con otro vehículo.' },
      { kind: 'agent', text: 'Primero: ¿está usted y los demás implicados bien? ¿Necesita ambulancia o policía?' },
      { kind: 'user', text: 'Todos bien, solo daños materiales.' },
      { kind: 'sys', text: 'Abriendo expediente · verificando póliza activa…' },
      { kind: 'agent', text: 'Perfecto. Necesito la matrícula del otro vehículo y la dirección exacta del accidente.' },
      { kind: 'user', text: '1234 ABC, en la A-6 km 12 sentido Madrid.' },
      { kind: 'sys', text: 'Registrando datos en sistema de siniestros…' },
      { kind: 'agent', text: 'Expediente 2024-SR-4821 abierto. Le enviamos el parte amistoso al móvil. Un perito le contactará en menos de 24 h.' },
      { kind: 'call_end', text: '✓ Expediente abierto · Parte amistoso enviado por SMS' },
    ],
  },
  {
    code: '50',
    sector: 'Seguros',
    channel: 'Automatizacion',
    title: 'Peritaje fotográfico automático',
    tagline: 'Analiza las fotos del siniestro con visión artificial, estima el coste de reparación y asigna el taller.',
    url: 'ops.segurfacil.es/peritaje',
    agentName: 'Perito IA SegurFácil',
    avatar: '📷',
    kpis: ['Peritajes completados', 'Precisión de estimación', 'Tiempo de peritaje', 'Talleres asignados', 'Disputas de cliente'],
    fakePage: {
      type: 'generic-service',
      logo: 'SegurFácil',
      links: ['Operaciones', 'Expedientes', 'Peritaje', 'Talleres'],
      activeLink: 2,
      tagline: 'Gestión automatizada de siniestros',
      heading: 'Panel de peritaje digital',
      phone: '900 900 200',
      tiles: [
        { icon: '📷', label: 'Fotos recibidas', desc: 'Análisis con visión artificial' },
        { icon: '💰', label: 'Estimación', desc: 'Cálculo de reparación' },
        { icon: '🔧', label: 'Taller asignado', desc: 'Red concertada' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Expediente 2024-SR-4821 · 6 fotografías recibidas vía app' },
      { kind: 'sys', text: 'Analizando daños con visión artificial: parachoque trasero + faro derecho' },
      { kind: 'sys', text: 'Consultando base de precios de taller homologado en Madrid…' },
      { kind: 'agent', text: 'Análisis completado: parachoque trasero (sustitución) y faro derecho (sustitución). Reparación estimada: 1.240–1.580 €.' },
      { kind: 'sys', text: 'Cobertura verificada · franquicia: 300 € · sin pérdida total' },
      { kind: 'agent', text: 'El siniestro no supera umbral de pérdida total. Derivando a taller concertado con recogida a domicilio. ¿Confirma el cliente?' },
      { kind: 'sys', text: 'Cliente confirma vía app · coordinando recogida de vehículo para mañana' },
      { kind: 'banner', text: '✓ Peritaje completado · Taller asignado · Recogida mañana 09:00 h' },
    ],
  },

  // ─── ENERGÍA ──────────────────────────────────────────────────────────────────
  {
    code: '54',
    sector: 'Energía',
    channel: 'Chat',
    title: 'Alta de suministro',
    tagline: 'Guía al cliente por el proceso de alta de luz y gas, verifica el CUPS y tramita el cambio de titularidad.',
    url: 'energiaverde.es',
    agentName: 'Asistente EnergíaVerde',
    avatar: '⚡',
    kpis: ['Altas tramitadas', 'Tiempo de gestión', 'Errores de CUPS', 'Abandonos del proceso', 'CSAT'],
    fakePage: {
      type: 'generic-service',
      logo: 'EnergíaVerde',
      links: ['Tarifas', 'Alta', 'Mi cuenta', 'Contacto'],
      activeLink: 1,
      tagline: '100 % energía renovable',
      heading: 'Luz y gas verde para tu hogar',
      phone: '900 700 700',
      tiles: [
        { icon: '⚡', label: 'Luz', desc: 'Tarifa solar garantizada' },
        { icon: '🔥', label: 'Gas', desc: 'Compensado con biogás' },
        { icon: '🌱', label: 'Verde 2.0', desc: 'Pack luz + gas con descuento' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Me mudo la semana que viene y necesito dar de alta la luz y el gas en mi nuevo piso.' },
      { kind: 'sys', text: 'Verificando disponibilidad de suministro en la dirección indicada…' },
      { kind: 'agent', text: 'Para gestionar el alta necesito el número de CUPS (está en el cuadro eléctrico o en el contrato anterior). ¿Lo tienes?' },
      { kind: 'user', text: 'ES0021000012345678ZF.' },
      { kind: 'sys', text: 'Consultando CUPS · verificando titular anterior…' },
      { kind: 'agent', text: 'Suministro activo con otro titular. Te propongo la tarifa Verde 2.0: 0,12 €/kWh con solar garantizado al 100 %. Alta en 24 h hábiles. ¿Procedo?' },
      { kind: 'user', text: 'Sí, adelante.' },
      { kind: 'sys', text: 'Tramitando cambio de titularidad · notificando distribuidora…' },
      { kind: 'agent', text: 'Alta tramitada. Recibirás confirmación en 24 h. El primer recibo llegará a finales de mes.' },
      { kind: 'banner', text: '✓ Alta tramitada · Tarifa Verde 2.0 · Activación en 24 h' },
    ],
  },
  {
    code: '53',
    sector: 'Energía',
    channel: 'Voz',
    title: 'Lectura de contador por voz',
    tagline: 'Recoge la lectura del cliente por teléfono, valida contra el histórico y registra en el sistema de facturación.',
    url: 'energiaverde.es/lecturas',
    agentName: 'Asistente EnergíaVerde',
    avatar: '📟',
    kpis: ['Lecturas recogidas', 'Validaciones incorrectas', 'Llamadas redirigidas', 'Tiempo medio', 'Facturaciones estimadas evitadas'],
    fakePage: {
      type: 'generic-service',
      logo: 'EnergíaVerde',
      links: ['Tarifas', 'Alta', 'Mi cuenta', 'Contacto'],
      activeLink: 2,
      tagline: '100 % energía renovable',
      heading: 'Luz y gas verde para tu hogar',
      phone: '900 700 700',
      tiles: [
        { icon: '📟', label: 'Lecturas', desc: 'Comunica tu contador' },
        { icon: '📄', label: 'Facturas', desc: 'Consulta e historial' },
        { icon: '🔧', label: 'Averías', desc: 'Incidencias de suministro' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 900 700 700' },
      { kind: 'agent', text: 'EnergíaVerde, servicio de lecturas. Dígame su número de contrato o dirección.' },
      { kind: 'user', text: 'Contrato 88234551, soy Teresa Blanco.' },
      { kind: 'sys', text: 'Verificando titular y último período registrado…' },
      { kind: 'agent', text: 'Hola Teresa. Tu último período registrado es de octubre. ¿Me das la lectura del contador de gas que ves en el dial?' },
      { kind: 'user', text: 'Sí, pone 04821.' },
      { kind: 'sys', text: 'Validando lectura contra media histórica…' },
      { kind: 'agent', text: 'Lectura validada: 4.821 m³. Consumo del período: 189 m³, dentro de la media habitual. La factura se generará el día 5.' },
      { kind: 'call_end', text: '✓ Lectura 4.821 m³ registrada · Factura pendiente día 5' },
    ],
  },
  {
    code: '56',
    sector: 'Energía',
    channel: 'Automatizacion',
    title: 'Gestión automática de cortes',
    tagline: 'Detecta la avería, estima el impacto, notifica a los afectados y prioriza clientes vulnerables.',
    url: 'ops.energiaverde.es/incidencias',
    agentName: 'NOC EnergíaVerde',
    avatar: '🔌',
    kpis: ['Clientes notificados', 'Tiempo de notificación', 'Vulnerables atendidos', 'Reclamaciones recibidas', 'Tiempo de reposición'],
    fakePage: {
      type: 'generic-service',
      logo: 'EnergíaVerde',
      links: ['Operaciones', 'Incidencias', 'Red', 'Informes'],
      activeLink: 1,
      tagline: 'Centro de control de red',
      heading: 'Gestión de incidencias en tiempo real',
      phone: '900 700 800',
      tiles: [
        { icon: '⚡', label: 'Estado de red', desc: 'Centros de transformación' },
        { icon: '🔌', label: 'Cortes activos', desc: 'Suministros afectados' },
        { icon: '🚨', label: 'Prioridades', desc: 'Clientes vulnerables' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Alerta: avería en CT-0034 · zona afectada: 342 suministros' },
      { kind: 'sys', text: 'Estimando duración: 3–4 h (equipo técnico en ruta)' },
      { kind: 'agent', text: 'Activando protocolo: notificando a 342 clientes por SMS y email con hora estimada de reposición (14:30 h).' },
      { kind: 'sys', text: 'Identificando clientes prioritarios (equipos médicos, colectivos vulnerables)…' },
      { kind: 'agent', text: '3 clientes con equipos médicos detectados. Activando atención especializada y evaluando grupo electrógeno de emergencia.' },
      { kind: 'sys', text: 'Suministro repuesto a las 14:18 h · verificando reconexiones automáticas…' },
      { kind: 'banner', text: '✓ Suministro repuesto · 342 notificaciones · 0 incidencias prioritarias sin atender' },
    ],
  },

  // ─── EDUCACIÓN ────────────────────────────────────────────────────────────────
  {
    code: '61',
    sector: 'Educación',
    channel: 'Chat',
    title: 'Tutor académico 24/7',
    tagline: 'Explica conceptos, resuelve dudas paso a paso y propone ejercicios adaptados al nivel del alumno.',
    url: 'campusonline.es/tutor',
    agentName: 'Tutor CampusOnline',
    avatar: '🎓',
    kpis: ['Dudas resueltas', 'Tiempo medio de respuesta', 'Satisfacción del alumno', 'Accesos nocturnos', 'Progresión en ejercicios'],
    fakePage: {
      type: 'platform',
      logo: 'CampusOnline',
      links: ['Inicio', 'Cursos', 'Tutor IA', 'Mi perfil'],
      activeLink: 2,
      menuItems: ['Dashboard', 'Mis cursos', 'Tutorías', 'Foros'],
      activeMenu: 2,
      heading: 'Tutor IA · Cálculo I',
      stats: [
        { label: 'Cursos activos', value: '3' },
        { label: 'Horas este mes', value: '14,5 h' },
      ],
      notifications: [
        { icon: '📚', text: 'Nuevo material en Cálculo I', time: 'hace 2 h' },
        { icon: '💬', text: 'El tutor respondió tu pregunta', time: 'hace 5 h' },
      ],
    },
    steps: [
      { kind: 'user', text: 'No entiendo cómo calcular la derivada de f(x) = x³ · ln(x).' },
      { kind: 'sys', text: 'Consultando base de conocimiento de Cálculo I…' },
      { kind: 'agent', text: 'Para derivar un producto usamos la regla del producto: (u·v)′ = u′·v + u·v′. Aquí u = x³ y v = ln(x).' },
      { kind: 'agent', text: 'u′ = 3x² y v′ = 1/x. Entonces: f′(x) = 3x²·ln(x) + x³·(1/x) = 3x²·ln(x) + x². ¿Quieres practicar con otro ejemplo?' },
      { kind: 'user', text: 'Sí, uno parecido.' },
      { kind: 'agent', text: 'Intenta calcular g(x) = x²·eˣ con la misma regla y dime el resultado — te confirmo si es correcto.' },
    ],
  },
  {
    code: '59',
    sector: 'Educación',
    channel: 'Voz',
    title: 'Admisiones por voz',
    tagline: 'Atiende las llamadas de candidatos, informa del programa, cualifica el perfil y agenda la reunión con el asesor.',
    url: 'campusonline.es/admisiones',
    agentName: 'Admisiones CampusOnline',
    avatar: '📞',
    kpis: ['Leads cualificados', 'Citas con asesor', 'Conversión a matrícula', 'Duración de llamada', 'CSAT'],
    fakePage: {
      type: 'platform',
      logo: 'CampusOnline',
      links: ['Programas', 'Admisiones', 'Campus', 'Contacto'],
      activeLink: 1,
      menuItems: ['Dashboard', 'Programas', 'Admisiones', 'Comunidad'],
      activeMenu: 2,
      heading: 'Proceso de admisión',
      stats: [
        { label: 'Plazas disponibles', value: '12' },
        { label: 'Próximo inicio', value: 'Oct 2025' },
      ],
      notifications: [
        { icon: '🎓', text: 'MBA Executive · nueva edición abierta', time: 'Hoy' },
        { icon: '📅', text: 'Open Day virtual · 15 agosto', time: 'En 3 semanas' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 91 500 44 00' },
      { kind: 'agent', text: 'CampusOnline, admisiones. ¿En qué programa está interesado?' },
      { kind: 'user', text: 'En el MBA. ¿Cuándo empieza la próxima edición y qué requisitos pide?' },
      { kind: 'sys', text: 'Consultando catálogo de programas y plazas disponibles…' },
      { kind: 'agent', text: 'La próxima edición del MBA empieza en octubre. Requisitos: titulación universitaria y 2 años de experiencia profesional. ¿Cumples ambos?' },
      { kind: 'user', text: 'Sí, tengo un grado en ADE y llevo 4 años trabajando.' },
      { kind: 'agent', text: 'Perfil válido. Quedan 12 plazas. ¿Quieres que un asesor académico te llame esta semana para explicarte el proceso?' },
      { kind: 'user', text: 'Sí, el martes por la tarde.' },
      { kind: 'sys', text: 'Registrando lead · asignando asesor…' },
      { kind: 'call_end', text: '✓ Lead cualificado · Cita con asesor: martes 16:00 h' },
    ],
  },
  {
    code: '63',
    sector: 'Educación',
    channel: 'Automatizacion',
    title: 'Automatización de matrículas',
    tagline: 'Valida documentación, verifica el pago y activa el acceso al LMS sin intervención del equipo de admisiones.',
    url: 'ops.campusonline.es/matriculas',
    agentName: 'Matrícula Automática',
    avatar: '📋',
    kpis: ['Matrículas completadas', 'Errores documentales detectados', 'Tiempo de activación', 'Revisiones manuales', 'Tasa de completitud'],
    fakePage: {
      type: 'platform',
      logo: 'CampusOnline',
      links: ['Operaciones', 'Matrículas', 'Documentación', 'Pagos'],
      activeLink: 1,
      menuItems: ['Dashboard', 'Pendientes', 'Validadas', 'Incidencias'],
      activeMenu: 1,
      heading: 'Bandeja de matrículas',
      stats: [
        { label: 'Pendientes', value: '14' },
        { label: 'Completadas hoy', value: '8' },
      ],
      notifications: [
        { icon: '✅', text: 'Carla V. · documentación completa', time: 'Hace 5 min' },
        { icon: '⚠️', text: 'Marco L. · título universitario pendiente', time: 'Hace 1 h' },
      ],
    },
    steps: [
      { kind: 'sys', text: 'Alumna Carla V. · solicitud de matrícula MBA Oct-2025 · 5 documentos recibidos' },
      { kind: 'sys', text: 'Validando DNI ✓ · Título universitario ✓ · CV ✓ · Carta de motivación ✓' },
      { kind: 'sys', text: 'Verificando pago de reserva: 500 € recibidos el 12/06 ✓' },
      { kind: 'agent', text: 'Documentación completa y pago confirmado. Generando contrato de matrícula y acceso al LMS.' },
      { kind: 'sys', text: 'Enviando contrato a Carla V. para firma digital…' },
      { kind: 'sys', text: 'Firma recibida · activando cuenta en CampusOnline LMS…' },
      { kind: 'banner', text: '✓ Matrícula completada · Acceso LMS activado · Email de bienvenida enviado' },
    ],
  },

  // ─── TECH/SAAS ────────────────────────────────────────────────────────────────
  {
    code: '68',
    sector: 'Tech/SaaS',
    channel: 'Chat',
    title: 'Knowledge base técnica',
    tagline: 'Responde preguntas técnicas de los clientes buscando en la documentación de producto con respuestas exactas.',
    url: 'docs.flowdesk.io',
    agentName: 'Soporte técnico FlowDesk',
    avatar: '💻',
    kpis: ['Tickets deflectados', 'Precisión de respuesta', 'Tiempo de resolución', 'CSAT', 'Escalados a ingeniería'],
    fakePage: {
      type: 'platform',
      logo: 'FlowDesk',
      links: ['Docs', 'API', 'Soporte', 'Estado'],
      activeLink: 0,
      menuItems: ['Inicio', 'Guías', 'API Reference', 'Webhooks'],
      activeMenu: 3,
      heading: 'Documentación FlowDesk',
      stats: [
        { label: 'Artículos', value: '284' },
        { label: 'Versión API', value: 'v3.2.1' },
      ],
      notifications: [
        { icon: '🆕', text: 'Webhook events · nueva documentación', time: 'Hoy' },
        { icon: '🔄', text: 'API v3.2.1 · changelog disponible', time: 'Ayer' },
      ],
    },
    steps: [
      { kind: 'user', text: '¿Cómo configuro el webhook para recibir notificaciones cuando se cierra un ticket?' },
      { kind: 'sys', text: 'Buscando en documentación técnica de webhooks…' },
      { kind: 'agent', text: 'Ve a Ajustes → Integraciones → Webhooks. El evento que necesitas es `ticket.closed`. El payload incluye ticket_id, status, resolved_at y agent_id.' },
      { kind: 'user', text: '¿Y si necesito filtrar solo los tickets de una categoría concreta?' },
      { kind: 'agent', text: 'En el campo "Filtros del webhook" añade `category = billing` (o la categoría que necesites). El webhook solo se disparará para tickets de esa categoría.' },
      {
        kind: 'cards',
        cards: [
          { name: 'Ejemplo payload', price: 'JSON', stock: 'ticket.closed · category:billing', why: '{"ticket_id":"T-8821","category":"billing","resolved_at":"2025-07-24T10:42:00Z"}' },
        ],
      },
      { kind: 'agent', text: 'Si quieres, pruebo el webhook en tu entorno de staging. Dime la URL y el secret.' },
    ],
  },
  {
    code: '66',
    sector: 'Tech/SaaS',
    channel: 'Voz',
    title: 'Cualificación de leads',
    tagline: 'Llama a los leads entrantes, recoge el BANT completo y los pasa calificados al Account Executive.',
    url: 'flowdesk.io/contacto',
    agentName: 'SDR IA FlowDesk',
    avatar: '🎯',
    kpis: ['Leads contactados', 'BANT completados', 'Citas con AE', 'Tiempo de cualificación', 'Coste por lead cualificado'],
    fakePage: {
      type: 'platform',
      logo: 'FlowDesk',
      links: ['Producto', 'Precios', 'Clientes', 'Contacto'],
      activeLink: 3,
      menuItems: ['Dashboard', 'Pipeline', 'Leads', 'Informes'],
      activeMenu: 2,
      heading: 'Pipeline de ventas',
      stats: [
        { label: 'Leads esta semana', value: '47' },
        { label: 'Cualificados', value: '18' },
      ],
      notifications: [
        { icon: '🎯', text: 'Pablo R. · formulario enviado hace 2 h', time: 'Hace 2 h' },
        { icon: '✅', text: 'Ana G. · BANT completo · AE asignado', time: 'Hace 4 h' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada saliente · lead Pablo R. · whitepaper descargado hace 2 h' },
      { kind: 'agent', text: 'Hola Pablo, soy el asistente de FlowDesk. Vi que descargaste nuestro whitepaper de automatización. ¿Tienes dos minutos?' },
      { kind: 'user', text: 'Sí, claro.' },
      { kind: 'agent', text: '¿Cuántos agentes de soporte tiene tu equipo y qué herramienta usáis actualmente?' },
      { kind: 'user', text: 'Somos 12 agentes y usamos Zendesk, pero nos resulta caro para lo que nos da.' },
      { kind: 'agent', text: 'FlowDesk tiene integración nativa con Zendesk para migración sin fricción. ¿Cuál es vuestro volumen mensual de tickets?' },
      { kind: 'user', text: 'Unos 3.500 tickets al mes.' },
      { kind: 'sys', text: 'Puntuación BANT: Necesidad ✓ · Volumen ✓ · Perfil ✓ · Timing pendiente' },
      { kind: 'agent', text: '¿Cuándo necesitaríais tener la solución operativa?' },
      { kind: 'user', text: 'En los próximos 2 meses.' },
      { kind: 'sys', text: 'Lead cualificado · BANT completo · asignando a Account Executive' },
      { kind: 'call_end', text: '✓ Lead caliente · BANT completo · AE notificado' },
    ],
  },
  {
    code: '69',
    sector: 'Tech/SaaS',
    channel: 'Automatizacion',
    title: 'Gestión automática de tickets',
    tagline: 'Clasifica, prioriza y agrupa los tickets entrantes según SLA, tipo y duplicados sin intervención humana.',
    url: 'ops.flowdesk.io/tickets',
    agentName: 'Triage Engine FlowDesk',
    avatar: '🎫',
    kpis: ['Tickets procesados', 'Duplicados agrupados', 'SLA cumplidos', 'Tiempo de clasificación', 'Escalados incorrectos'],
    fakePage: {
      type: 'platform',
      logo: 'FlowDesk',
      links: ['Operaciones', 'Tickets', 'SLA', 'Informes'],
      activeLink: 1,
      menuItems: ['Dashboard', 'Cola activa', 'Resueltos', 'SLA'],
      activeMenu: 1,
      heading: 'Cola de tickets · tiempo real',
      stats: [
        { label: 'Nuevos hoy', value: '47' },
        { label: 'SLA en riesgo', value: '2' },
      ],
      notifications: [
        { icon: '🚨', text: '9 tickets de Facturación · alta prioridad SLA', time: 'Ahora' },
        { icon: '🔗', text: '8 duplicados de #BUG-2241 agrupados', time: 'Hace 2 min' },
      ],
    },
    steps: [
      { kind: 'sys', text: '47 tickets nuevos en cola · análisis de clasificación iniciado' },
      { kind: 'sys', text: 'Clasificando por tipo: Bug (12) · Configuración (18) · Facturación (9) · Feature request (8)' },
      { kind: 'agent', text: '9 tickets de "Facturación" detectados — alta prioridad según SLA. Asignando automáticamente al equipo de billing.' },
      { kind: 'sys', text: '12 tickets de "Bug" analizados: 8 duplicados del issue #BUG-2241 (ya en resolución)' },
      { kind: 'agent', text: '8 tickets duplicados agrupados y vinculados a #BUG-2241. Respuesta automática enviada a clientes con ETA de resolución.' },
      { kind: 'sys', text: '4 tickets de Bug únicos derivados a ingeniería con severidad P2' },
      { kind: 'banner', text: '✓ 47 tickets procesados · 8 duplicados agrupados · 0 SLA incumplidos' },
    ],
  },
];
