export const DEMOS = [
  {
    code: '01',
    sector: 'Retail',
    channel: 'Chat',
    title: 'Chatbot recomendador',
    tagline: 'Entiende una necesidad y recomienda producto en stock, sin inventar precio ni disponibilidad.',
    url: 'runnersandco.com',
    agentName: 'Asistente de tienda',
    avatar: '🛍️',
    kpis: ['CTR', 'Add-to-cart', 'Conversión', 'Ticket medio', 'Devoluciones'],
    fakePage: {
      type: 'shop',
      logo: 'Runners&Co',
      links: ['Hombre', 'Mujer', 'Ofertas', 'Guía de tallas'],
      activeLink: -1,
      eyebrow: 'Nueva colección SS26',
      heading: 'Corre con la pisada a tu favor',
      sub: 'Envío gratis a partir de 60 € · Devoluciones en 30 días.',
      cta: 'Ver colección',
      sectionTitle: 'Más vendidos en running',
      products: [
        { emoji: '👟', name: 'Asics Gel-Kayano 30', price: '94,90 €' },
        { emoji: '👟', name: 'Brooks Adrenaline GTS 23', price: '99,00 €' },
        { emoji: '👟', name: 'New Balance 860v13', price: '89,00 €' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Hola, busco zapatillas para correr. Tengo pisada pronadora y un presupuesto de unos 100€.' },
      { kind: 'sys', text: 'Consultando catálogo, stock y precio en tiempo real…' },
      { kind: 'agent', text: 'Estas tres opciones encajan con tu pisada y tu presupuesto, todas en stock:' },
      {
        kind: 'cards',
        cards: [
          { name: 'Asics Gel-Kayano 30', price: '94,90 €', stock: 'En stock · 3 tallas', why: 'Estabilidad para pisada pronadora, soporte medial en la entresuela.' },
          { name: 'Brooks Adrenaline GTS 23', price: '99,00 €', stock: 'En stock', why: 'Amortiguación guiada, la más elegida por perfiles similares.' },
          { name: 'New Balance 860v13', price: '89,00 €', stock: 'Últimas unidades', why: 'Buena relación estabilidad/precio, dentro de tu presupuesto.' },
        ],
      },
      { kind: 'user', text: 'Me quedo con las Brooks, talla 42.' },
      { kind: 'agent', text: 'Añadidas al carrito: Brooks Adrenaline GTS 23, talla 42. ¿Quieres que te avise si bajan de precio?' },
    ],
  },
  {
    code: '33',
    sector: 'Logística',
    channel: 'Voz',
    title: 'Tracking de envío por voz',
    tagline: 'Identifica el paquete, informa del estado en tiempo real y gestiona la incidencia sin intervención humana.',
    url: 'logisticx.es/contacto',
    agentName: 'Asistente LogisticX',
    avatar: '📦',
    kpis: ['Resolución en llamada', 'Duración media', 'Reentradas en 24 h', 'Redireccionamientos gestionados', 'CSAT de voz'],
    fakePage: {
      type: 'contact',
      logo: 'LogisticX',
      links: ['Seguimiento', 'Recogidas', 'Incidencias', 'Contacto'],
      activeLink: 3,
      heading: '¿Cómo podemos ayudarte?',
      phone: '91 234 56 78',
      departments: [
        { icon: '📦', label: 'Seguimiento de envíos', desc: 'Localiza tu paquete en tiempo real' },
        { icon: '⚠️', label: 'Incidencias y reclamaciones', desc: 'Pérdidas, daños y retrasos' },
        { icon: '🚚', label: 'Recogidas a domicilio', desc: 'Programa una recogida sin coste' },
      ],
    },
    steps: [
      { kind: 'call_start', text: 'Llamada entrante · 91 234 56 78' },
      { kind: 'agent', text: 'Hola, soy el asistente de LogisticX. ¿Cómo puedo ayudarte?' },
      { kind: 'user', text: 'Quiero saber dónde está mi paquete. El número de seguimiento es ES987654321.' },
      { kind: 'sys', text: 'Consultando TMS · Localizando paquete ES987654321…' },
      { kind: 'agent', text: 'Tu paquete salió del centro de Madrid a las 7:14 h y está en reparto. Llegará hoy antes de las 14:00 h.' },
      { kind: 'user', text: '¿Y si no estoy en casa?' },
      { kind: 'agent', text: 'Puedo programar una segunda entrega para mañana o redirigirlo a un punto de recogida. ¿Cuál prefieres?' },
      { kind: 'user', text: 'El punto de recogida, por favor.' },
      { kind: 'sys', text: 'Localizando puntos cercanos · Reservando plaza…' },
      { kind: 'agent', text: 'Listo. Tu paquete irá al punto UPS en Calle Mayor 15, disponible mañana desde las 9:00 h. Te envío el código de recogida por SMS.' },
      { kind: 'call_end', text: '✓ Llamada completada · SMS de confirmación enviado' },
    ],
  },
  {
    code: '06',
    sector: 'Retail',
    channel: 'Automatizacion',
    title: 'Automatización de devoluciones',
    tagline: 'Sin intervención humana en el camino feliz: solicitud, verificación, aprobación y reembolso en un único flujo.',
    url: 'devoluciones.runnersandco.com',
    agentName: 'Devoluciones automáticas',
    avatar: '📦',
    kpis: ['Tiempo de ciclo', 'Straight-through processing', 'Fraude detectado', 'Coste por devolución', 'Reembolsos fallidos'],
    fakePage: {
      type: 'returns',
      logo: 'Runners&Co',
      links: ['Pedidos', 'Devoluciones', 'Contacto'],
      activeLink: 1,
      heading: 'Devuelve tu pedido en 3 pasos',
      sub: 'Sin colas de atención: la mayoría de devoluciones se resuelven al momento.',
      steps: [
        { label: 'Solicita la devolución', desc: 'Indica el pedido y el motivo' },
        { label: 'Envía el paquete', desc: 'Con la etiqueta que te enviamos' },
        { label: 'Recibe tu reembolso', desc: 'En 2-3 días tras la recepción' },
      ],
      formFields: ['Número de pedido', 'Email de la compra'],
      formButton: 'Buscar pedido',
    },
    steps: [
      { kind: 'user', text: 'Quiero devolver un artículo del pedido #7734, no me convence.' },
      { kind: 'sys', text: 'Recuperando pedido y verificando plazo y estado…' },
      { kind: 'sys', text: 'Analizando evidencia del artículo y comprobando antifraude…' },
      { kind: 'agent', text: 'Devolución aprobada automáticamente. Aquí tienes tu etiqueta RMA — solo tienes que llevar el paquete a tu punto de envío.' },
      { kind: 'sys', text: 'Artículo recibido en almacén · reembolso de 42,90 € iniciado' },
      { kind: 'agent', text: 'Reembolso confirmado. El importe llegará a tu método de pago original en 2-3 días laborables.' },
      { kind: 'banner', text: '✓ Completado sin intervención humana' },
    ],
  },
  {
    code: '17',
    sector: 'Banca',
    channel: 'Integracion',
    title: 'Chat-core bancario',
    tagline: 'Consulta y opera sobre CRM, core y riesgo en un único flujo autenticado, con trazabilidad íntegra.',
    url: 'backoffice.bancax.es',
    agentName: 'Agente BancaX',
    avatar: '🏦',
    kpis: ['Operaciones completadas', 'Errores de integración', 'Latencia media', 'Disponibilidad', 'Trazabilidad de acciones'],
    fakePage: {
      type: 'portal',
      logo: 'BancaX',
      links: ['Clientes', 'Operaciones', 'Límites', 'Auditoría'],
      activeLink: 0,
      heading: 'Portal de gestión de clientes',
      sub: 'Acceso autenticado · Entorno de producción',
      menuItems: ['Búsqueda de cliente', 'Nueva operación', 'Gestión de límites', 'Historial de auditoría'],
      activeMenu: 0,
    },
    steps: [
      { kind: 'user', text: 'Busca la situación completa del cliente con IBAN ES91 2100 0418 4502 0005 1332.' },
      { kind: 'multi_query', queries: ['CRM cliente', 'Core bancario', 'Historial productos'] },
      {
        kind: 'data_panel',
        fields: [
          { label: 'Cliente', value: 'María López' },
          { label: 'Saldo disponible', value: '12.340 €' },
          { label: 'Límite crédito', value: '15.000 €' },
          { label: 'Última operación', value: 'Ayer · 220 €' },
        ],
      },
      { kind: 'agent', text: 'María López, cuenta activa desde 2018. Saldo 12.340 € y crédito utilizado 12.340 €/15.000 €. ¿Qué operación quieres gestionar?' },
      { kind: 'user', text: 'Amplía el límite de crédito a 20.000 €.' },
      { kind: 'sys', text: 'Verificando score crediticio · Comprobando límites regulatorios…' },
      { kind: 'agent', text: 'Operación preparada. El nuevo límite sería 20.000 €. ¿Confirmas?' },
      { kind: 'user', text: 'Confirmar.' },
      { kind: 'sys', text: 'Actualizando core bancario · Registrando en auditoría…' },
      { kind: 'banner', text: '✓ Límite actualizado · Confirmación enviada al cliente' },
    ],
  },
];
