export const DEMOS = [
  {
    code: '01',
    sector: 'Retail',
    channel: 'Chat',
    title: 'Chatbot recomendador',
    tagline: 'Entiende una necesidad y recomienda producto en stock, sin inventar precio ni disponibilidad.',
    url: 'runnersandco.com',
    agentName: 'Asistente de tienda',
    avatar: '🛍️',
    kpis: ['CTR', 'Add-to-cart', 'Conversión', 'Ticket medio', 'Devoluciones'],
    fakePage: {
      type: 'shop',
      logo: 'Runners&Co',
      links: ['Hombre', 'Mujer', 'Ofertas', 'Guía de tallas'],
      activeLink: -1,
      eyebrow: 'Nueva colección SS26',
      heading: 'Corre con la pisada a tu favor',
      sub: 'Envío gratis a partir de 60 € · Devoluciones en 30 días.',
      cta: 'Ver colección',
      sectionTitle: 'Más vendidos en running',
      products: [
        { emoji: '👟', name: 'Asics Gel-Kayano 30', price: '94,90 €' },
        { emoji: '👟', name: 'Brooks Adrenaline GTS 23', price: '99,00 €' },
        { emoji: '👟', name: 'New Balance 860v13', price: '89,00 €' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Hola, busco zapatillas para correr. Tengo pisada pronadora y un presupuesto de unos 100€.' },
      { kind: 'sys', text: 'Consultando catálogo, stock y precio en tiempo real…' },
      { kind: 'agent', text: 'Estas tres opciones encajan con tu pisada y tu presupuesto, todas en stock:' },
      {
        kind: 'cards',
        cards: [
          { name: 'Asics Gel-Kayano 30', price: '94,90 €', stock: 'En stock · 3 tallas', why: 'Estabilidad para pisada pronadora, soporte medial en la entresuela.' },
          { name: 'Brooks Adrenaline GTS 23', price: '99,00 €', stock: 'En stock', why: 'Amortiguación guiada, la más elegida por perfiles similares.' },
          { name: 'New Balance 860v13', price: '89,00 €', stock: 'Últimas unidades', why: 'Buena relación estabilidad/precio, dentro de tu presupuesto.' },
        ],
      },
      { kind: 'user', text: 'Me quedo con las Brooks, talla 42.' },
      { kind: 'agent', text: 'Añadidas al carrito: Brooks Adrenaline GTS 23, talla 42. ¿Quieres que te avise si bajan de precio?' },
    ],
  },
  {
    code: '04',
    sector: 'Retail',
    channel: 'Chat',
    title: 'Chat postventa',
    tagline: 'Autentica, clasifica, consulta política vigente y resuelve — o escala si no hay elegibilidad clara.',
    url: 'ayuda.runnersandco.com',
    agentName: 'Atención al cliente',
    avatar: '💬',
    kpis: ['Resolución 1er contacto', 'AHT', 'CSAT', 'Reapertura', 'Respuestas sustentadas'],
    fakePage: {
      type: 'help',
      logo: 'Runners&Co',
      links: ['Pedidos', 'Cambios', 'Pagos', 'Contacto'],
      activeLink: 1,
      heading: '¿En qué podemos ayudarte?',
      searchPlaceholder: 'Busca por pedido, envío, pagos…',
      sectionTitle: 'Temas populares',
      tiles: [
        { icon: '📦', label: 'Pedidos y envíos', desc: 'Seguimiento, plazos y modificaciones' },
        { icon: '↩️', label: 'Cambios y devoluciones', desc: 'Política de 30 días y etiquetas' },
        { icon: '💳', label: 'Pagos y facturación', desc: 'Métodos de pago y facturas' },
        { icon: '👤', label: 'Mi cuenta', desc: 'Datos, direcciones y contraseña' },
      ],
    },
    steps: [
      { kind: 'user', text: 'Hola, el pedido #4821 me ha llegado y la talla me queda pequeña, ¿puedo cambiarla?' },
      { kind: 'sys', text: 'Verificando pedido y política de cambios vigente…' },
      { kind: 'agent', text: 'Tu pedido #4821 es elegible para cambio de talla (dentro de 30 días, sin usar). Te he generado la etiqueta, la recibirás por email en unos minutos.' },
      { kind: 'alt', tag: 'Camino alternativo ·', text: 'si no fuera elegible, el caso se escala a un agente humano en lugar de resolverse automáticamente.' },
      { kind: 'user', text: 'Perfecto, muchas gracias.' },
      { kind: 'agent', text: 'De nada. Ticket #4821-CT actualizado — te avisaremos en cuanto recibamos el artículo.' },
    ],
  },
  {
    code: '06',
    sector: 'Retail',
    channel: 'Automatizacion',
    title: 'Automatización de devoluciones',
    tagline: 'Sin intervención humana en el camino feliz: solicitud, verificación, aprobación y reembolso en un único flujo.',
    url: 'devoluciones.runnersandco.com',
    agentName: 'Devoluciones automáticas',
    avatar: '📦',
    kpis: ['Tiempo de ciclo', 'Straight-through processing', 'Fraude detectado', 'Coste por devolución', 'Reembolsos fallidos'],
    fakePage: {
      type: 'returns',
      logo: 'Runners&Co',
      links: ['Pedidos', 'Devoluciones', 'Contacto'],
      activeLink: 1,
      heading: 'Devuelve tu pedido en 3 pasos',
      sub: 'Sin colas de atención: la mayoría de devoluciones se resuelven al momento.',
      steps: [
        { label: 'Solicita la devolución', desc: 'Indica el pedido y el motivo' },
        { label: 'Envía el paquete', desc: 'Con la etiqueta que te enviamos' },
        { label: 'Recibe tu reembolso', desc: 'En 2-3 días tras la recepción' },
      ],
      formFields: ['Número de pedido', 'Email de la compra'],
      formButton: 'Buscar pedido',
    },
    steps: [
      { kind: 'user', text: 'Quiero devolver un artículo del pedido #7734, no me convence.' },
      { kind: 'sys', text: 'Recuperando pedido y verificando plazo y estado…' },
      { kind: 'sys', text: 'Analizando evidencia del artículo y comprobando antifraude…' },
      { kind: 'agent', text: 'Devolución aprobada automáticamente. Aquí tienes tu etiqueta RMA — solo tienes que llevar el paquete a tu punto de envío.' },
      { kind: 'sys', text: 'Artículo recibido en almacén · reembolso de 42,90 € iniciado' },
      { kind: 'agent', text: 'Reembolso confirmado. El importe llegará a tu método de pago original en 2-3 días laborables.' },
      { kind: 'banner', text: '✓ Completado sin intervención humana' },
    ],
  },
];
